language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip setuptools tox twine
script:
  - tox --recreate
  - git diff --exit-code
jobs:
  include:
    - stage: publish
      if: branch = master AND repo = Zac-HD/hypothesis-jsonschema
      script: python setup.py sdist bdist_wheel && twine upload --skip-existing dist/*
